/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AppController;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Item;

/**
 *
 * @author USER
 */
public class AdminFrame extends javax.swing.JFrame {

    public static AppController controller;

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        ShowInfoPanel.setVisible(false);
        controller = new AppController();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowItemsBut = new javax.swing.JButton();
        newMedBut = new javax.swing.JButton();
        ShowInfoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ilist = new javax.swing.JComboBox<>();
        ShowInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));

        ShowItemsBut.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ShowItemsBut.setForeground(new java.awt.Color(0, 153, 153));
        ShowItemsBut.setText("Show All Items");
        ShowItemsBut.setPreferredSize(new java.awt.Dimension(150, 70));
        ShowItemsBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowItemsButActionPerformed(evt);
            }
        });

        newMedBut.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        newMedBut.setForeground(new java.awt.Color(0, 153, 153));
        newMedBut.setText("New Medicine");
        newMedBut.setPreferredSize(new java.awt.Dimension(150, 70));
        newMedBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMedButActionPerformed(evt);
            }
        });

        ShowInfoPanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setText("Select a Medicine to Show : ");

        jButton2.setText("Show Quantity");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Show Price");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ilist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ilist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShowInfoPanelLayout = new javax.swing.GroupLayout(ShowInfoPanel);
        ShowInfoPanel.setLayout(ShowInfoPanelLayout);
        ShowInfoPanelLayout.setHorizontalGroup(
            ShowInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShowInfoPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ilist, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(ShowInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ShowInfoPanelLayout.setVerticalGroup(
            ShowInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ShowInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(ilist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ShowInfo.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        ShowInfo.setForeground(new java.awt.Color(0, 153, 153));
        ShowInfo.setText("Show Medicine Info");
        ShowInfo.setPreferredSize(new java.awt.Dimension(200, 70));
        ShowInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(ShowInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newMedBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ShowItemsBut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newMedBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowItemsBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(ShowInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMedButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMedButActionPerformed
        // TODO add your handling code here:
        ShowInfoPanel.setVisible(false);
        NewMedicine ins = new NewMedicine();
        ins.setTitle("Inserting new medicine");
        ins.setVisible(true);

    }//GEN-LAST:event_newMedButActionPerformed

    private void ShowItemsButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowItemsButActionPerformed

        //out.setText(controller.PrintAllItems());
       MedicinesList m = new MedicinesList();
       m.setTitle("Our Medicines List");
       m.setVisible(true);
       
       
    }//GEN-LAST:event_ShowItemsButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String iname = ilist.getSelectedItem().toString();
        Double p = controller.getItemPrice(iname);
        //out.setText("the price of " + iname + " is " + p);
        JOptionPane.showMessageDialog(this, "The price of " + iname + " is " + p + " LL", "Notification", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String iname = ilist.getSelectedItem().toString();
        int qty = controller.getTotalQuantity(iname);
        //out.setText("the quantity of " + iname + " is " + qty);
        JOptionPane.showMessageDialog(this,"The quantity of " + iname + " is " + qty, "Notification", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void ilistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilistActionPerformed
//        if(!controller.getItemList().isEmpty())  {
//            ilist.removeAllItems();
//            for (int j = 0; j < controller.getItemList().size(); j++) {
//                System.out.println("for loop start");
//                ilist.addItem(controller.getItemList().get(j).getItemName());
//                System.out.println("Item added to ilist");
//            }
//        }
    }//GEN-LAST:event_ilistActionPerformed

    private void ShowInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowInfoActionPerformed
        ShowInfoPanel.setVisible(true);

        if (!controller.getItemList().isEmpty()) {
            ilist.removeAllItems();
            for (int j = 0; j < controller.getItemList().size(); j++) {
                System.out.println("for loop start");
                ilist.addItem(controller.getItemList().get(j).getItemName());
                System.out.println("Item added to ilist");
            }
        }
    }//GEN-LAST:event_ShowInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShowInfo;
    private javax.swing.JPanel ShowInfoPanel;
    private javax.swing.JButton ShowItemsBut;
    private javax.swing.JComboBox<String> ilist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton newMedBut;
    // End of variables declaration//GEN-END:variables
}
